In [13]:
# Importing the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
# Loading the various data files

duration = pd.read_csv('../data/raw/actual_duration.csv')
appointments = pd.read_csv('../data/raw/appointments_regional.csv')
regions = pd.read_excel('../data/raw/ICB_Region_Codes.xlsx')
categories = pd.read_excel('../data/raw/national_categories.xlsx')
tweets = pd.read_csv('../data/raw/tweets.csv')

In [15]:
# Checking the info of each df

duration.info()
appointments.info()
regions.info()
categories.info()
tweets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137793 entries, 0 to 137792
Data columns (total 8 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   sub_icb_location_code      137793 non-null  object
 1   sub_icb_location_ons_code  137793 non-null  object
 2   sub_icb_location_name      137793 non-null  object
 3   icb_ons_code               137793 non-null  object
 4   region_ons_code            137793 non-null  object
 5   appointment_date           137793 non-null  object
 6   actual_duration            137793 non-null  object
 7   count_of_appointments      137793 non-null  int64
dtypes: int64(1), object(7)
memory usage: 8.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 596821 entries, 0 to 596820
Data columns (total 7 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   icb_ons_code                       596821 non-null  object
 1   appointment_month                  596821 non-null  object
 2   appointment_status                 596821 non-null  object
 3   hcp_type                           596821 non-null  object
 4   appointment_mode                   596821 non-null  object
 5   time_between_book_and_appointment  596821 non-null  object
 6   count_of_appointments              596821 non-null  int64
dtypes: int64(1), object(6)
memory usage: 31.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   NHSER22CD  7 non-null      object
 1   NHSER22NM  7 non-null      object
dtypes: object(2)
memory usage: 244.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 817394 entries, 0 to 817393
Data columns (total 8 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   appointment_date       817394 non-null  datetime64[ns]
 1   icb_ons_code           817394 non-null  object
 2   sub_icb_location_name  817394 non-null  object
 3   service_setting        817394 non-null  object
 4   context_type           817394 non-null  object
 5   national_category      817394 non-null  object
 6   count_of_appointments  817394 non-null  int64
 7   appointment_month      817394 non-null  object
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 49.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1174 entries, 0 to 1173
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   tweet_id                 1174 non-null   int64
 1   tweet_full_text          1174 non-null   object
 2   tweet_entities           1174 non-null   object
 3   tweet_entities_hashtags  1007 non-null   object
 4   tweet_metadata           1174 non-null   object
 5   tweet_retweet_count      1174 non-null   int64
 6   tweet_favorite_count     1174 non-null   int64
 7   tweet_favorited          1174 non-null   bool
 8   tweet_retweeted          1174 non-null   bool
 9   tweet_lang               1174 non-null   object
dtypes: bool(2), int64(3), object(5)
memory usage: 75.8+ KB

In [27]:
# Changing the data types to ensure they correctly reflect the data
duration['appointment_date'] = pd.to_datetime(duration['appointment_date'])

appointments['appointment_month'] = pd.to_datetime(appointments['appointment_month'])

In [28]:
duration.info()
appointments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137793 entries, 0 to 137792
Data columns (total 8 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   sub_icb_location_code      137793 non-null  object
 1   sub_icb_location_ons_code  137793 non-null  object
 2   sub_icb_location_name      137793 non-null  object
 3   icb_ons_code               137793 non-null  object
 4   region_ons_code            137793 non-null  object
 5   appointment_date           137793 non-null  datetime64[ns]
 6   actual_duration            137793 non-null  object
 7   count_of_appointments      137793 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 8.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 596821 entries, 0 to 596820
Data columns (total 7 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   icb_ons_code                       596821 non-null  object
 1   appointment_month                  596821 non-null  datetime64[ns]
 2   appointment_status                 596821 non-null  object
 3   hcp_type                           596821 non-null  object
 4   appointment_mode                   596821 non-null  object
 5   time_between_book_and_appointment  596821 non-null  object
 6   count_of_appointments              596821 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 31.9+ MB

In [ ]:
# Checking for duplicated values in the data
duration[duration.duplicated()]

Empty DataFrame
Columns: [NHSER22CD, NHSER22NM]
Index: []

In [35]:
regions[regions.duplicated()]

Empty DataFrame
Columns: [NHSER22CD, NHSER22NM]
Index: []

In [36]:
appointments[appointments.duplicated()]

,icb_ons_code,appointment_month,appointment_status,hcp_type,appointment_mode,time_between_book_and_appointment,count_of_appointments
19292,E54000044,2020-01-01,Attended,GP,Home Visit,Unknown / Data Quality,1
19308,E54000044,2020-01-01,Attended,GP,Unknown,Unknown / Data Quality,2
19374,E54000044,2020-01-01,DNA,GP,Home Visit,8 to 14 Days,1
19417,E54000044,2020-01-01,DNA,Unknown,Face-to-Face,2 to 7 Days,1
19419,E54000044,2020-01-01,DNA,Unknown,Face-to-Face,Same Day,6
...,...,...,...,...,...,...,...
596809,E54000050,2022-06-01,Unknown,Unknown,Telephone,15 to 21 Days,1
596812,E54000050,2022-06-01,Unknown,Unknown,Telephone,More than 28 Days,1
596814,E54000050,2022-06-01,Unknown,Unknown,Unknown,1 Day,2
596817,E54000050,2022-06-01,Unknown,Unknown,Unknown,22 to 28 Days,8
596820,E54000050,2022-06-01,Unknown,Unknown,Unknown,Same Day,10